sudo: false

language: node_js
node_js:
- "node"

matrix:
  include:
    - os: linux
      dist: trusty

before_install:
- npm install -g typescript tslint

install:
- npm install
- npm run build

script:
- npm test
- npm run coverage:upload